### ISSUE TITLE
发现一个bug，当Activity有两个布局，添加了不同的Fragment时，会出现问题

### ISSUE THREAD

**Issue by davidgerka** [AndyJennifer/AndroidxLazyLoad#6]
**如下图所示，点击按钮后，会将f1和f2都隐藏了，只显示f3，而我是想要显示f1和f3**

![WX20211103-111453](https://user-images.githubusercontent.com/13624423/140005564-476c8812-dc40-4136-b623-2a73c83d454a.png)
![WX20211103-111612](https://user-images.githubusercontent.com/13624423/140005575-0772761e-65a9-4f2e-a4ae-def6a4876c7b.png)

**Comment by davidgerka** [comment]
按照你的思路，仔细想一下，如下图的代码是否可行？也不需要提前load Fragment了，当需要添加并且显示Fragment时才去调用下图的方法。有一个前提就是：Fragment不能写在布局里面
![image](https://user-images.githubusercontent.com/13624423/140293768-9db648f0-c130-4ade-8a4b-282b73c85f3b.png)

**Comment by AndyJennifer** [comment]
ShowFragment 默认就会将其他Fragment 隐藏掉，Show+hide 这种情况只适用于界面是单fragment 的情况
